checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - magento/framework

filter:
  excluded_paths:
    - "Test/"

build:
  dependencies:
    before:
      - 'echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_COMPOSER_USERNAME}\",\"password\":\"${MAGENTO_COMPOSER_PASSWORD}\"}}}" > auth.json'
      - 'composer config allow-plugins true'

  environment:
    php:
      version: 7.4.33
