<?php
/*
 * Clive Walkden
 *
 *  NOTICE OF LICENSE
 *
 *  This source file is subject to the Open Software License (OSL 3.0)
 *  that is bundled with this package in the file LICENSE.
 *  It is also available through the world-wide-web at this URL:
 *  http://opensource.org/licenses/osl-3.0.php
 *
 *  @category    Clive Walkden
 *  @package     CliveWalkden_Usersnap
 *  @copyright   Copyright (c) Clive Walkden (https://clivewalkden.co.uk)
 *  @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

// @codingStandardsIgnoreFile
/* @var $block \CliveWalkden\Usersnap\Block\Backend */
/* @var $escaper \Magento\Framework\Escaper */
?>
<!-- BEGIN USERSNAP CODE {literal} -->
<script>
    window.onUsersnapCXLoad = function(api) {
        api.init(<?= $block->getConfig()?>);
        window.Usersnap = api;
        api.show('<?= $block->getProjectApiKey()?>')
    }
    var script = document.createElement('script');
    script.defer = 1;
    script.src = 'https://widget.usersnap.com/global/load/<?= $escaper->escapeUrl($block->getWidgetId())?>?onload=onUsersnapCXLoad';
    document.getElementsByTagName('head')[0].appendChild(script);
</script>
<!-- {/literal} END USERSNAP CODE -->
