<?php
/**
 * Clive Walkden
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Clive Walkden
 * @package     CliveWalkden_Usersnap
 * @copyright   Copyright (c) 2017 Clive Walkden (https://clivewalkden.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */
?>
<div style="background:#EAF0EE; border:1px solid #CCCCCC; margin-bottom:10px; padding:11px 0 0 10px;">
    <h4>
        <?php
        /*
        <img width="224px" height="60px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/><br><br>
        */
        ?>
        <div style="padding-left: 30px;">
            <p> <strong style="color:#EA7601;"><?php echo __('Usersnap v') ?><?php echo $this->getVersion() ?><?php echo __(' by') ?></strong> <a target="_blank" href="https://clivewalkden.co.uk"><strong>Clive Walkden</strong></a></p>
        </div>
    </h4>
</div>
